spring.application.name=AuthenticationSystem
spring.datasource.url=jdbc:postgresql://ep-dark-fire-aikug5ox-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Adding the dialect explicitly to prevent the "Unable to determine Dialect" error
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.jwt.secret=mySuperSecretJwtKeyForTesting123456789
app.jwt.expiration=86400000
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

