spring.application.name=AuthenticationSystem

# Database Configuration (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-dark-fire-aikug5ox-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Hikari Connection Pool Tuning for Neon Serverless
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=45000


# Template Engine
spring.thymeleaf.check-template-location=false

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Configuration
app.jwt.secret=mySuperSecretJwtKeyForTesting123456789
app.jwt.expiration=86400000

# Cloudinary Integration
cloudinary.cloud-name=${YOUR_CLOUD_NAME}
cloudinary.api-key=${YOUR_API_KEY}
cloudinary.api-secret=${YOUR_API_SECRET}