# Application Name
spring.application.name=AuthenticationSystem

# Database Configuration (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-crimson-shadow-amhyad7o-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_a59ZKAoJBuvG
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Adding the dialect explicitly to prevent the "Unable to determine Dialect" error
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nwangwudinma22@gmail.com
spring.mail.password=mqkumohuzzhxgyxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.access-token.secret=ThisIsASuperLongAccessTokenSecretKeyAtLeast32Bytes
jwt.access-token.expiration-ms=3600000
jwt.refresh-token.secret=AnotherSuperLongRefreshTokenSecretKeyAtLeast32Bytes
jwt.refresh-token.expiration-ms=604800000